#lang racket
(define (suma-cuadrados p h s)
  (if (< h p)
      (begin
        (set! s (+ s (expt h 2)))
        (suma-cuadrados p (+ h 1) s)
        )
      (printf "la suma de cuadrados es de ~a" s)
      )
  )
(define (ejercicio)
  (define p 0)
  (define h 0)
  (display "el parametro debe ser mayor que ")
  (set! h (read))
  (display "el parametro debe ser menor que ")
  (set! p (read))
  (suma-cuadrados p h 0)
  )
(ejercicio)