#lang racket
(define (suma-enteros p h s)
  (if (<= h p)
      (begin
        (set! s (+ s 1))
        (suma-enteros p (+ h 1) s))
      (display s)
      )
  )
(define (ejercicio)
  (define p 0)
  (define h 0)
  (display "el parametro debe ser mayor que ")
  (set! h (read))
  (display "el parametro debe ser menor que ")
  (set! p (read))
  (suma-enteros p h 0)
  )
(ejercicio)