#lang racket
(define (suma p h s)
  (if (<= h p)
      (begin
        (set! s (+ h s))
        (suma p (+ h 1) s))
      (printf "la suma es de: ~a" s)
      )
  )
(define (ejercicio)
  (define p 0)
  (define h 0)
  (display "el parametro debe ser mayor que ")
  (set! h (read))
  (display "el parametro debe ser menor que ")
  (set! p (read))
  (suma p h 0)
  )
(ejercicio)